version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/perennial-leagues"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    groups:
      dev-dependencies:
        dependency-type: "development"
