const teamNormalizationMap: { [key: string]: string } = {
    "A. Taranto": "Taranto",
    "A.Doria": "Andrea Doria",
    "A.M.C.": "Associazione Milanese Calcio",
    "AC Libertas": "",
    "AC Milanese": "AC Milanese Corvetto 1920",
    "AZ Picerno": "",
    "Acireale": "",
    "Acquapozzillo": "",
    "Acqui": "",
    "Adelaide Nicastro": "",
    "Adriese": "",
    "Aeronautica Torino": "",
    "Aesernia": "",
    "Afragolese": "",
    "Aglianese": "",
    "Akragas": "",
    "Alba": "",
    "Alba Audace": "",
    "Alba Roma": "",
    "Albalatrastevere": "",
    "Albanova": "",
    "Albese": "",
    "Albinese": "",
    "AlbinoLeffe": "",
    "Albissola": "",
    "Alcamo": "",
    "Alcione": "",
    "Alessandria": "",
    "Alessandrina": "",
    "Alghero": "",
    "Almas": "",
    "Almas Roma": "",
    "Altamura": "",
    "Alzano": "",
    "Alzano Virescit": "",
    "Amatori": "",
    "Amatori Torino": "",
    "Ambrosiana": "Inter",
    "Ambrosiana Inter": "Inter",
    "Ambrosiana-Inter": "Inter",
    "Ancona": "Ancona",
    "Ancona Matelica": "Ancona",
    "Ancona-Matelica": "Ancona",
    "Anconitana": "Ancona",
    "Anconitana Bianchi": "Ancona",
    "Anconitana-Bianchi": "Ancona",
    "Andrea Doria": "Andrea Doria",
    "Andrea Doria*": "Andrea Doria",
    "Andria BAT": "",
    "Angizia": "",
    "Angizia Luco": "",
    "Angri": "",
    "Aosta": "",
    "Aprilia": "",
    "Aquila": "",
    "Aquila Montevarchi": "",
    "Arezzo": "",
    "Arona": "",
    "Arrone": "",
    "Arsenale Taranto": "Taranto",
    "Arsenaltaranto": "Taranto",
    "Arzachena": "",
    "Arzanese": "",
    "Arzignano Valchiampo": "",
    "Ascoli": "",
    "Asti": "",
    "Asti TSC": "",
    "Astrea": "",
    "Atalanta": "",
    "Atalanta U23": "",
    "Atl. Roma": "Atletico Roma",
    "Atletico Catania": "",
    "Atletico Leonzio": "",
    "Atletico Roma": "",
    "Audace": "",
    "Audace Cerignola": "",
    "Audace Ferrara": "",
    "Audace Livorno": "",
    "Audace Roma": "",
    "Audace SME": "",
    "Audace Taranto": "",
    "Audace Torino": "",
    "Audacia Napoli": "",
    "Audax": "",
    "Audax M.": "",
    "Aurora Desio": "",
    "Ausonia": "",
    "Ausonia P.G.": "Ausonia",
    "Ausonia Pro Gorla": "Ausonia",
    "Ausonia*": "Ausonia",
    "Avellino": "",
    "Aversa Normanna": "",
    "Avezzano": "",
    "Bacoli Sibilla Flegrea": "",
    "Bagnolese": "",
    "Banco Roma": "Banco di Roma",
    "Banco di Roma": "",
    "Baracca": "",
    "Baracca Lugo": "Baracca",
    "Bari": "",
    "Barletta": "",
    "Bassano": "Bassano Virtus",
    "Bassano V.": "Bassano Virtus",
    "Bassano Virtus": "",
    "Battipagliese": "",
    "Bellaria": "",
    "Bellaria Igea Marina": "Bellaria",
    "Belluno": "",
    "Benevento": "",
    "Bentegodi": "Bentegodi Verona", 
    "Bentegodi Verona": "",
    "Bergamasca": "",
    "Biellese": "",
    "Bisceglie": "",
    "Bitonto": "",
    "Boca San Lazzaro": "",
    "Bologna": "",
    "Bolognese": "",
    "Bolzano": "",
    "Borgo a Buggiano": "",
    "Borgosesia": "",
    "Borzacchini Terni": "",
    "Bra": "",
    "Brasiliano": "",
    "Brembillese": "",
    "Brescello": "",
    "Brescia": "",
    "Brindisi": "",
    "C.R.D.A. Monfalcone": "",
    "C.S Firenze": "C.S. Firenze",
    "C.S. Firenze": "",
    "C.di Sangro": "Castel di Sangro",
    "CRDA Monfalcone": "Monfalcone",
    "CS Firenze": "C.S. Firenze",
    "Cagliari": "",
    "Cairese": "",
    "Calcio Caravaggese": "",
    "Caldiero": "",
    "Campania": "Campania Puteolana",
    "Campania P.": "Campania Puteolana",
    "Campania Puteolana": "",
    "Campobasso": "",
    "Canavese": "",
    "Canicattì": "",
    "Caratese": "",
    "Caravaggese": "",
    "Carbonia": "",
    "Carbosarda": "",
    "Carignano": "",
    "Carpenedolo": "",
    "Carpi": "",
    "Carrarese": "",
    "Casale": "",
    "Casalecchio": "",
    "Casalotti": "",
    "Casarano": "",
    "Casatese": "",
    "Casertana": "",
    "Casoria": "",
    "Cassino": "",
    "Casteggio": "",
    "Castel Rigone": "",
    "Castel S.Pietro": "Castel San Pietro",
    "Castel San Pietro": "",
    "Castel di Sangro": "",
    "Castellarano": "",
    "Castelnuovo": "",
    "Castelsangro": "",
    "Castiglione": "",
    "Castrovillari": "",
    "Catania": "",
    "Catanzarese": "",
    "Catanzaro": "",
    "Cattolica": "",
    "Cavese": "",
    "Cecina": "",
    "Celano": "",
    "Celano Olimpia": "Celano",
    "Centese": "",
    "Cerretese": "",
    "Cerveteri": "",
    "Cervia": "",
    "Cesena": "",
    "Cesenatico": "",
    "Chiasso": "",
    "Chieti": "",
    "Chievo": "Chievo Verona",
    "Chievo Verona": "",
    "Chioggia Sottomarina": "",
    "Cirio": "",
    "Cisco Lodigiani": "",
    "Cisco Roma": "",
    "Cittadella": "",
    "Città di Castello": "",
    "Città di Cerveteri": "",
    "Città di Jesolo": "",
    "Civitanovese": "",
    "Civitavecchia": "",
    "Civitavecchiese": "Civitavecchia",
    "ClodiaSottomarina": "Clodia Sottomarina",
    "Clodiasottomarina": "Clodia Sottomarina",
    "Codogno": "",
    "Colleferro": "",
    "Colligiana": "",
    "Comense": "",
    "Como": "",
    "Conegliano": "",
    "Cosenza": "",
    "Cossatese": "",
    "Crema": "",
    "Cremapergo": "",
    "Cremonese": "",
    "Crevalcore": "",
    "Crociati Noceto": "",
    "Crotone": "",
    "Cuneo": "",
    "CuoioCappiano": "",
    "Cuoiopelli": "",
    "Cuoiopelli Cappiano Romaiano": "Cuoiopelli", 
    "Cynthia": "",
    "Del Duca Ascoli": "Ascoli",
    "Delta Porto Tolle": "",
    "Derthona": "",
    "Dolo": "",
    "Dominante": "",
    "Ebolitana": "",
    "Edera Trieste": "",
    "Elpidiense": "",
    "Empoli": "",
    "Enna": "",
    "Enotria": "",
    "Enotria G.": "Enotria",
    "Enotria Goliardo": "Enotria",
    "Entella": "Virtus Entella",
    "Entella Bacezza": "Virtus Entella",
    "Ercolanese": "",
    "Esperia": "",
    "FBC Bari": "Bari",
    "FC Torinese": "",
    "FEDIT": "",
    "Faenza": "",
    "Fanfulla": "",
    "Fano": "",
    "Fasano": "",
    "Feltrese": "",
    "FeralpiSalò": "Feralpisalò",
    "Feralpisalò": "",
    "Ferentino": "",
    "Fermana": "",
    "Fidelis": "Fidelis Andria",
    "Fidelis Andria": "",
    "Figline": "",
    "Fiorente": "",
    "Fiorentina": "",
    "Fiorenzuola": "",
    "Firenze": "Fiorentina",
    "Firenze FBC": "Fiorentina",
    "Fiumana": "",
    "Florentia Viola": "",
    "Foggia": "",
    "Foggia & Incedit": "Foggia",
    "Foligno": "",
    "Fondi": "",
    "Forlì": "",
    "Formia": "",
    "Forti e Liberi": "",
    "Fortis Juventus": "",
    "Fortitudo": "Fortitudo Pro Roma",
    "Fortitudo Pro Roma": "",
    "Francavilla": "",
    "Frattese": "",
    "Frosinone": "",
    "G.C. Cappuccini": "",
    "GC Grifone": "",
    "GS Bolognese": "Bolognese",
    "Galatina": "",
    "Gallaratese": "",
    "Gallipoli": "",
    "Gavinovese": "",
    "Gavorrano": "",
    "Gela": "",
    "Gela J.T.": "Gela",
    "Gelbison": "",
    "Genoa": "",
    "Genova": "Genoa",
    "Genova 1893": "Genoa",
    "Gerbi": "",
    "Gerbi Pisa": "",
    "Giacomense": "",
    "Giana Erminio": "",
    "Giarre": "",
    "Ginnastica": "",
    "Ginnastica Torino": "",
    "Gioiese": "",
    "Giorgione": "",
    "Giovani Calciatori": "GC Grifone",
    "Gioventù Brindisi": "",
    "Giugliano": "",
    "Giulianova": "",
    "Gladiator": "",
    "Gorizia": "",
    "Gozzano": "",
    "Grifone": "GC Grifone",
    "Grion Pola": "",
    "Grosseto": "",
    "Grumese": "",
    "Gualdo": "",
    "Gubbio": "",
    "Hellas": "Hellas Verona",
    "Hellas Verona": "",
    "HinterReggio": "",
    "Ideale": "",
    "Igea": "",
    "Igea Virtus": "",
    "Ilva Maddalena": "",
    "Imola": "",
    "Imolese": "",
    "Imperia": "",
    "Inter": "",
    "Internaples": "Internazionale Naples",
    "Internapoli": "Internazionale Napoli",
    "Internazionale": "Internazionale Napoli",
    "Internazionale Napoli": "",
    "Internazionale Torino": "",
    "Iperzola": "",
    "Ischia": "",
    "Ischia Isolaverde": "",
    "Isernia": "",
    "Isola Liri": "",
    "Itala Firenze": "",
    "Itala San Marco": "",
    "Ivrea": "",
    "Jesi": "",
    "Jesina": "",
    "Juniorcasale": "",
    "Juve Domo": "",
    "Juve Stabia": "",
    "Juventina Gela": "",
    "Juventus": "",
    "Juventus Audax": "",
    "Juventus Domo": "",
    "Juventus Italia": "",
    "Juventus Next Gen": "",
    "Juventus Roma": "",
    "Juventus Stabia": "",
    "Juventus U23": "",
    "Juveterranova Gela": "",
    "Kroton": "",
    "L'Aquila": "",
    "L.R. Vicenza": "Vicenza",
    "L.V.P.A. Frascati": "",
    "LVPA Frascati": "",
    "La Dominante": "Sampdoria",
    "La Palma": "",
    "Lambro": "",
    "Lanciano": "",
    "Lanerossi Vicenza": "Vicenza",
    "Latina": "",
    "Lazio": "",
    "Lecce": "",
    "Lecco": "",
    "Leffe": "",
    "Legnago": "",
    "Legnago Salus": "Legnago",
    "Legnanesi": "",
    "Legnano": "",
    "Leonzio": "",
    "Libertas": "",
    "Libertas Firenze": "",
    "Libertas Palermo": "",
    "Liberty": "",
    "Licata": "",
    "Liguria": "Sampierdarenese",
    "Liguria FBC": "Sampierdarenese",
    "Livorno": "",
    "Lodigiani": "",
    "Lucca": "Lucchese",
    "Lucchese": "",
    "Lucchese Libertas": "Lucchese",
    "Lumezzane": "",
    "Lupa Castelli Romani": "",
    "Lupa Piacenza": "",
    "Lupa Roma": "",
    "MATER": "",
    "Ma.Co.Bi.Asti": "",
    "Macerata": "Maceratese",
    "Maceratese": "",
    "Magenta": "",
    "Maglie": "",
    "Manfredonia": "",
    "Manlio Cavagnaro": "",
    "Mantova": "",
    "Mantovana": "",
    "Marsala": "",
    "Martina": "Martina Franca",
    "Martina Franca": "",
    "Marzoli Palazzolo": "",
    "Marzotto": "",
    "Marzotto Valdagno": "",
    "Massese": "",
    "Massiminiana": "",
    "Matelica": "",
    "Matera": "",
    "Meda": "",
    "Meda 1913": "Meda",
    "Mediolanum": "",
    "Melfi": "",
    "Messina": "",
    "Messinese": "",
    "Mestre": "",
    "Mestrina": "",
    "Mezzocorona": "",
    "Milan": "",
    "Milan Futuro": "",
    "Milanese": "US Milanese",
    "Milano": "Milan",
    "Milazzo": "",
    "Mira": "",
    "Mobilieri Ponsacco": "",
    "Modena": "",
    "Modica": "",
    "Molassana": "",
    "Molfetta": "",
    "Molinella": "",
    "Moncalieri": "",
    "Monfalcone": "",
    "Monfalconese C.N.T.": "Monfalcone",
    "Monfalconese CNT": "Monfalcone",
    "Monopoli": "",
    "Monselice": "",
    "Montebelluna": "",
    "Montecatini": "",
    "Montecchio": "",
    "Monterosi Tuscia": "",
    "Montevarchi": "",
    "Montichiari": "",
    "Monza": "",
    "Morolo": "",
    "Morro d'Oro": "",
    "Naples": "",
    "Napoli": "",
    "Nardò": "",
    "Nazionale Emilia": "",
    "Nazionale L.": "Nazionale Lombardia",
    "Nazionale Lombardia": "",
    "Neapolis": "",
    "Nissa": "",
    "Nocerina": "",
    "Noicattaro": "",
    "Nola": "",
    "Novara": "",
    "Novarese": "",
    "Novese": "",
    "Nuorese": "",
    "Nuova Igea": "",
    "Olbia": "",
    "Oltrepò": "",
    "Olympia": "",
    "Omegna": "",
    "Orceana": "",
    "Osimana": "",
    "Ospitaletto": "",
    "Ostia Mare": "",
    "Ozo Mantova": "",
    "P.Vercelli": "Pro Vercelli",
    "Padova": "",
    "Paganese": "",
    "Palazzolo": "",
    "Palermo": "",
    "Palermo Juventina": "",
    "Palermo-Juventina": "Palermo Juventina",
    "Palmese": "",
    "Panigale": "",
    "Parma": "",
    "Pastore": "",
    "Paternò": "",
    "Pavia": "",
    "Pergocrema": "",
    "Pergolettese": "",
    "Perugia": "",
    "Pescara": "",
    "Pescina": "",
    "Pescina VG": "Pescina",
    "Petrarca": "",
    "Piacenza": "",
    "Pianese": "",
    "Piemonte": "",
    "Pietrasanta": "",
    "Pievigina": "",
    "Pineto": "",
    "Piombino": "",
    "Pisa": "",
    "Pistoiese": "",
    "Pizzighettone": "",
    "Poggese": "",
    "Poggibonsi": "",
    "Pomezia": "",
    "Pontedera": "",
    "Pordenone": "",
    "Portocivitanovese": "",
    "Portogruaro": "",
    "Portogruaro-Summaga": "Portogruaro",
    "Potenza": "",
    "Prato": "",
    "Pro Belvedere": "",
    "Pro Caserta": "",
    "Pro Cavese": "",
    "Pro Cisterna": "",
    "Pro Gorizia": "",
    "Pro Italia": "",
    "Pro Livorno": "",
    "Pro Napoli": "",
    "Pro Patria": "",
    "Pro Piacenza": "",
    "Pro Roma": "",
    "Pro Sesto": "",
    "Pro Vasto": "",
    "Pro Vercelli": "",
    "Pro Vercelli*": "Pro Vercelli",
    "ProVercelli": "Pro Vercelli",
    "Puteolana": "",
    "R.M. Firenze": "",
    "Racing Fondi": "",
    "Racing Lib.": "Racing Libertas",
    "Racing Libertas": "",
    "Racing Roma": "",
    "Ragusa": "",
    "Rapallo Ruentes": "",
    "Ravenna": "",
    "Real Marcianise": "",
    "Real SPAL": "SPAL",
    "Real Vicenza": "",
    "Recanatese": "",
    "Reggiana": "",
    "Reggina": "",
    "Reggio Audace": "",
    "Renate": "",
    "Rende": "",
    "Rhodense": "",
    "Riccione": "",
    "Rieti": "",
    "Rimini": "",
    "Rivarolese": "",
    "Rizzoli": "",
    "Robur Siena": "",
    "Rodengo Saiano": "",
    "Roma": "",
    "Roman": "",
    "Romana": "",
    "Rondinella": "",
    "Rosetana": "",
    "Rovereto": "",
    "Rovigo": "",
    "Russi": "",
    "Rutigliano": "",
    "S. Angelo": "Sant'Angelo Lodigiano",
    "S. Angelo L.": "Sant'Angelo Lodigiano",
    "S.Anastasia": "Sant'Anastasia",
    "S.Elena Quartu": "Sant'Elena Quartu",
    "S.Torres": "Sassari Torres",
    "SC Lecce": "Lecce",
    "SIAI Marchetti": "",
    "SPAL": "",
    "SPES": "SPES Livorno",
    "SPES Livorno": "",
    "Sacilese": "",
    "Salernitana": "",
    "Salernitanaudax": "Salernitana",
    "Sambenedettese": "",
    "Sambonifacese": "",
    "Sampdoria": "",
    "Sampierd.": "Sampierdarenese",
    "Sampierdarenese": "",
    "San Donato Tavarnelle": "",
    "San Donà": "",
    "San Felice Normanna": "",
    "San Marino": "",
    "San Vito Benevento": "",
    "Sandona'": "Sandonà",
    "Sandonà": "",
    "Sangiovannese": "",
    "Sangiuliano City": "",
    "Sangiuseppese": "",
    "Sangiuseppese Neapolis": "Sangiuseppese",
    "Sangiustese": "",
    "Sanremese": "",
    "Sansepolcro": "",
    "Sansovino": "",
    "Sant'Anastasia": "",
    "Sant'Angelo": "Sant'Angelo Lodigiano",
    "Sant'Angelo Lodigiano": "",
    "Sant'Elena Quartu": "",
    "Santarcangelo": "",
    "Sarom Ravenna": "",
    "Saronno": "",
    "Sarzanese": "",
    "Sassari Torres": "",
    "Sassuolo": "",
    "Saviglianese": "",
    "Savoia": "",
    "Savona": "",
    "Savonese": "",
    "Scafatese": "",
    "Schio": "",
    "Seregno": "",
    "Serenissima": "",
    "Serenitas Spezia": "",
    "Sestrese": "",
    "Sestri Levante": "",
    "Sicula Leonzio": "",
    "Siena": "",
    "Simaz Popoli": "",
    "Simmenthal Monza": "Monza",
    "Simmenthal-Monza": "Monza",
    "Siracusa": "",
    "Solbiatese": "",
    "Solvay Rosignano": "",
    "Sora": "",
    "Sorrento": "",
    "Sorso": "",
    "Sottomarina": "",
    "Spal": "SPAL",
    "Speranza": "",
    "Spes": "Spes Genova",
    "Spes Genova": "",
    "Spezia": "",
    "Sporting Benevento": "Benevento",
    "Squinzano": "",
    "Stabia": "",
    "Stelvio": "",
    "Suzzara": "",
    "Südtirol": "Südtirol-Alto Adige",
    "Südtirol-Alto Adige": "",
    "Talmone Torino": "",
    "Tarantina": "",
    "Taranto": "",
    "Team Altamura": "",
    "Tebro Roma": "",
    "Telgate": "",
    "Tempio": "",
    "Teramo": "",
    "Ternana": "",
    "Terranova Gela": "",
    "Tevere": "",
    "Tevere Roma": "Tevere",
    "Thiene": "",
    "Tivoli": "",
    "Tolentino": "",
    "Toma Maglie": "",
    "Torinese": "US Torinese",
    "Torino": "",
    "Torres": "",
    "Torrese": "",
    "Trani": "",
    "Trapani": "",
    "Trento": "",
    "Trevigliese": "",
    "Treviso": "",
    "Tricase": "",
    "Triestina": "",
    "Tritium": "",
    "Turris": "",
    "Tuttocuoio": "",
    "US Milanese": "US Milanese",
    "US Milanese*": "US Milanese",
    "US Romana": "",
    "US Torinese": "",
    "Udine": "Udinese",
    "Udinese": "",
    "Union Clodiense": "",
    "Union Quinto": "",
    "Unione Venezia": "",
    "V. Lanciano": "Virtus Lanciano",
    "Vado": "",
    "Val di Sangro": "",
    "Valdagno": "",
    "Valdiano": "",
    "Valenzana": "",
    "Vallée d'Aoste": "",
    "Varese": "",
    "Vastese": "",
    "Veloces": "",
    "Venezia": "",
    "Venezia Mestre": "",
    "Verbania": "",
    "Vercellese": "",
    "Vercellesi Erranti": "",
    "Verona": "Hellas Verona",
    "Vezio Parducci Viareggio": "",
    "Viareggio": "",
    "Vibonese": "",
    "Vicenza": "",
    "Vico Equense": "",
    "Vigevanesi": "",
    "Vigevano": "",
    "Vigor": "",
    "Vigor Lamezia": "",
    "Vigor Senigallia": "",
    "Vigor Torino": "",
    "Villacidrese": "",
    "Virescit Bergamo": "",
    "Virescit Boccaleone": "",
    "Virtus": "",
    "Virtus Bologna": "",
    "Virtus Bolognese": "",
    "Virtus Casarano": "",
    "Virtus Entella": "",
    "Virtus Francavilla": "",
    "Virtus Juventusque": "",
    "Virtus Lanciano": "",
    "Virtus Verona": "",
    "Vis Pesaro": "",
    "Vis Sauro Pesaro": "",
    "Vita Nova": "",
    "Viterbese": "",
    "Viterbese Castrense": "",
    "Viterbo": "",
    "Vittoria": "",
    "Vittoria Roma": "",
    "Vittorio Veneto": "",
    "Voghera": "",
    "Vogherese": "",
    "Volontari Venezia": "",
    "Zenit Modena": "",
    "' Sheffield Weds": "Sheffield Weds",
    "105th Regiment": "",
    "105th Regiment FC": "105th Regiment",
    "1st Surrey Rifles": "",
    "1st Surrey Rifles FC": "1st Surrey Rifles",
    "93rd Highland Regiment": "",
    "93rd Highland Regiment FC": "93rd Highland Regiment",
    "AFC Ashington": "Ashington",
    "AFC Barrow": "Barrow",
    "AFC Bideford": "Bideford",
    "AFC Bournemouth": "Bournemouth",
    "AFC Consett": "Consett",
    "AFC Fylde": "Fylde",
    "AFC Gateshead": "Gateshead",
    "AFC Guiseley": "Guiseley",
    "AFC Horden Colliery Welfare": "Horden Colliery Welfare",
    "AFC Llanelli": "LLanelli",
    "AFC Mossley": "Mossley",
    "AFC New Brighton": "New Brighton",
    "AFC Newport County": "Newport County",
    "AFC Rochdale": "Rochdale",
    "AFC Shildon": "Shildon",
    "AFC Sudbury": "Sudbury",
    "AFC Sunderland": "Sunderland",
    "AFC Telford United": "Telford United",
    "AFC Totton": "Totton",
    "AFC Wellington": "Wellington",
    "AFC Weston-super-Mare": "Weston-super-Mare",
    "AFC Willington": "Willington",
    "AFC Wimbledon": "Wimbledon",
    "AFC Workington": "Workington",
    "AFC Wrexham": "Wrexham",
    "AP Leamington": "Leamington",
    "Aberdare Athletic": "",
    "Accrington": "",
    "Accrington FC": "Accrington",
    "Accrington S": "Accrington Stanley",
    "Accrington Stanley": "",
    "Acton": "",
    "Addlestone & Weybridge Town": "Addlestone & Weybridge",
    "Aldershot": "Aldershot Town",
    "Aldershot Town": "Aldershot",
    "Alfreton Town": "Alfreton",
    "Alton Town": "Alton",
    "Altrincham": "",
    "Altrincham FC": "Altrincham",
    "Alvechurch": "",
    "Amble": "",
    "Andover": "",
    "Annfield": "",
    "Annfield Plain": "",
    "Apsley": "",
    "Argonauts": "",
    "Arlesey Town": "Arlesey",
    "Armthorpe Welfare": "",
    "Arnold": "",
    "Arsenal": "",
    "Arsenal FC": "Arsenal",
    "Ashford": "",
    "Ashford Town": "Ashford",
    "Ashford Town (Kent)": "Ashford Town",
    "Ashington": "",
    "Ashton United": "",
    "Astley Bridge": "",
    "Aston Shakespeare": "",
    "Aston Unity": "",
    "Aston Villa": "",
    "Aston Villa FC": "Aston Villa",
    "Atherstone United": "",
    "Athletic Bournemouth": "",
    "Attercliffe": "",
    "Aveley": "",
    "Aylesbury United": "",
    "Banbury Spencer": "",
    "Banbury United": "",
    "Banbury Utd": "Banbury United",
    "Bangor City": "",
    "Barking": "Barking Town",
    "Barking Town": "Barking",
    "Barnes": "",
    "Barnes FC": "Barnes",
    "Barnet": "",
    "Barnet FC": "Barnet",
    "Barnsley": "",
    "Barnsley FC": "Barnsley",
    "Barnsley St Peter's": "Barnsley St. Peter's",
    "Barnsley St. Peter’s": "Barnsley St. Peter's",
    "Barnstaple Town": "Barnstaple",
    "Barrow": "",
    "Barrow AFC": "Barrow",
    "Barry": "",
    "Barry Town": "Barry",
    "Barton Rovers": "",
    "Basford Rovers": "",
    "Bashley": "",
    "Basingstoke Town": "Basingstoke",
    "Bath City": "",
    "Bedford Town": "Bedford",
    "Bedlington": "",
    "Bedlington Terriers": "",
    "Bedlington United": "",
    "Beighton Miners Welfare": "",
    "Belper Town": "Belper",
    "Bentley Colliery": "",
    "Berkhamsted Town": "Berkhamsted",
    "Bexley": "",
    "Bexley United": "",
    "Bicester Town": "Bicester",
    "Bideford": "",
    "Billericay Town": "Billericay",
    "Billingham Synthonia": "",
    "Bilston": "",
    "Birmingham": "",
    "Birmingham City": "",
    "Birmingham Corp. Tramways": "Birmingham Corporation Tramways",
    "Birmingham Corporation Tramways": "",
    "Birmingham Excelsior": "",
    "Birmingham Exclesior": "Birmingham Excelsior",
    "Birmingham St George's": "Birmingham St. George's",
    "Birmingham St. George’s": "Birmingham St. George's",
    "Birtley": "",
    "Bishop Auckland": "",
    "Bishop Auckland Church Institute": "",
    "Bishop's Stortford": "",
    "Bishop’s Stortford FC": "Bishop’s Stortford",
    "Blackburn": "Blackburn Rovers",
    "Blackburn Law": "",
    "Blackburn Olympic": "",
    "Blackburn Park Road": "",
    "Blackburn R": "",
    "Blackburn Rovers": "Blackburn Rovers",
    "Blackburn Rovers FC": "Blackburn Rovers",
    "Blackhall Colliery Welfare": "",
    "Blackpool": "",
    "Blackpool FC": "Blackpool",
    "Blackpool St John's": "Blackpool St. John's",
    "Blackpool St. John’s": "Blackpool St. John's",
    "Blue Star": "",
    "Blyth Spartans": "",
    "Bognor Regis Town": "Bognor Regis",
    "Bognor Regis Town FC": "Bognor Regis Town",
    "Bollington": "",
    "Bolton": "Bolton Wanderers",
    "Bolton Association": "",
    "Bolton Olympic": "",
    "Bolton Wand": "Bolton Wanderers",
    "Bolton Wanderer": "Bolton Wanderers",
    "Bolton Wanderers": "",
    "Bolton Wnaderers": "Bolton Wanderers",
    "Bootle": "",
    "Bootle FC": "Bootle",
    "Boreham Wood": "",
    "Boston": "",
    "Boston Town": "Boston",
    "Boston United": "",
    "Boston Utd": "Boston United",
    "Botwell Mission": "",
    "Bournemouth": "Bournemouth Rovers",
    "Bournemouth & Boscombe": "",
    "Bournemouth & Boscombe Ath": "Bournemouth & Boscombe",
    "Bournemouth & Boscombe Athletic": "Bournemouth & Boscombe",
    "Bournemouth Gasworks Athletic": "",
    "Bournemouth Rovers": "",
    "Bowers & Pitsea": "",
    "Brackley Town": "Brackley",
    "Bracknell Town": "Bracknell",
    "Bradford City": "",
    "Bradford PA": "Bradford Park Avenue",
    "Bradford Park Avenue": "",
    "Bradford Rovers": "",
    "Bradshaw": "",
    "Braintree Town": "Braintree",
    "Brandon Social": "",
    "Brandon United": "",
    "Brentford": "",
    "Brentford FC": "Brentford",
    "Brentwood": "",
    "Brentwood Town": "Brentwood",
    "Bridgwater Town": "Bridgwater",
    "Bridlington Town": "Bridlington",
    "Brierley Hill Alliance": "",
    "Brigg": "",
    "Brigg Britannia": "Brigg",
    "Brigg Brittania": "Brigg",
    "Brighton": "Brighton & Hove Albion",
    "Brighton & H Alb": "Brighton & Hove Albion",
    "Brighton & Hove": "Brighton & Hove Albion",
    "Brighton & Hove Albion": "",
    "Bristol City": "",
    "Bristol Rovers": "",
    "Brodsworth Main Colliery": "",
    "Bromley": "",
    "Bromsgrove Rovers": "",
    "Brondesbury": "",
    "Brush Sports": "",
    "Buckingham Town": "Buckingham",
    "Burnley": "",
    "Burnley FC": "Burnley",
    "Burscough": "",
    "Burslem Port Vale": "",
    "Burton Albion": "",
    "Burton Swifts": "",
    "Burton Town": "Burton",
    "Burton United": "",
    "Burton Wanderers": "",
    "Bury": "",
    "Bury FC": "Bury",
    "Bury Town": "Bury",
    "Buxton": "",
    "CBradford City": "",
    "CRoyal Engineers AFC": "CRoyal Engineers",
    "Caenarvon Wanderers": "",
    "Caernarfon Athletic": "",
    "Caernarfon Town": "Caernarfon",
    "Caernarvon Athletic": "",
    "Caernarvon Wanderers": "",
    "Calthorpe": "",
    "Camberley Town": "Camberley",
    "Cambridge City": "",
    "Cambridge Town": "Cambridge",
    "Cambridge United": "",
    "Cambridge University": "",
    "Cambridge University AFC": "Cambridge University",
    "Cambridge Utd": "Cambridge United",
    "Canterbury City": "",
    "Canvey Island": "",
    "Cardiff City": "",
    "Cardiff City FC": "Cardiff City",
    "Carlisle United": "",
    "Carlisle Utd": "Carlisle United",
    "Carnarvon Wanderers": "",
    "Carshalton Athletic": "",
    "Castleford Town": "Castleford",
    "Casuals": "",
    "Casuals FC": "Casuals",
    "Charlton": "",
    "Charlton Ath": "",
    "Charlton Athletic": "",
    "Chatam": "",
    "Chatham": "",
    "Chatham United FC": "Chatham United",
    "Chelmsford": "",
    "Chelmsford City": "",
    "Chelsea": "",
    "Chelsea FC": "Chelsea",
    "Cheltenham Town": "Cheltenham",
    "Chesham": "",
    "Chesham United": "",
    "Chesham Utd": "Chesham United",
    "Chester": "",
    "Chester City": "",
    "Chester St Oswald's": "Chester St. Oswald's",
    "Chester St. Oswald’s": "Chester St. Oswald's",
    "Chesterfield": "",
    "Chesterfield FC": "Chesterfield",
    "Chesterfield Spital": "",
    "Chichester City": "",
    "Chilton College": "",
    "Chilton Colliery Recr": "",
    "Chilton Colliery Recreation": "",
    "Chippenham Town": "Chippenham",
    "Chirk": "",
    "Chopwell Colliery": "",
    "Chorley": "",
    "Church": "",
    "Cinderford Town": "Cinderford",
    "Civil Service": "",
    "Civil Service FC": "Civil Service",
    "Clacton Town": "Clacton",
    "Clapham Rovers": "",
    "Clapton": "",
    "Clapton Orient": "",
    "Clarence": "",
    "Cleator Moor Celtic": "",
    "Cleethorpes Town": "Cleethorpes",
    "Cliftonville": "",
    "Cliftonville FC": "Cliftonville",
    "Clitheroe": "",
    "Clitheroe Low Moor": "",
    "Coalville Town": "Coalville",
    "Colchester United": "",
    "Colchester Utd": "Colchester United",
    "Colwyn Bay": "",
    "Colwyn Bay FC": "Colwyn Bay",
    "Concord Rangers": "",
    "Congleton Town": "Congleton",
    "Consett": "",
    "Corby Town": "Corby",
    "Corinthian": "",
    "Corinthian Casuals": "",
    "Corinthian FC": "Corinthian",
    "Corinthian-Casuals": "",
    "Corinthian-Casuals FC": "Corinthian-Casuals",
    "Corinthians": "",
    "Corinthinan": "",
    "Coventry City": "",
    "Coventry Sporting": "",
    "Cowlairs": "",
    "Crawley Town": "Crawley",
    "Cray Valley PM": "",
    "Cray Valley Paper Mills": "",
    "Creswell Colliery": "",
    "Crewe Alex": "",
    "Crewe Alexamdra": "",
    "Crewe Alexandra": "",
    "Crewe Alexandra FC": "Crewe Alexandra",
    "Crewe Alexandria": "",
    "Cristap Palace": "",
    "Crook": "",
    "Crook Town": "Crook",
    "Crookhall Colliery Welfare": "",
    "Crosswell's Brewery": "",
    "Crosswell’s Brewery": "",
    "Croydon": "",
    "Croydon Common": "",
    "Crusaders": "",
    "Crusaders FC": "Crusaders",
    "Crystal Palace": "",
    "Curzon Ashton": "",
    "Cystal Palace": "",
    "Dag & Red": "",
    "Dagenham": "",
    "Dagenham & Redbridge": "",
    "Dagenham Town": "Dagenham",
    "Darlington": "",
    "Darlington FC": "Darlington",
    "Dartford": "",
    "Darwen": "",
    "Darwen Old Wanderers": "",
    "Darwen Ramblers": "",
    "Davenham": "",
    "Dawdon Colliery Recreation": "",
    "Denaby United": "",
    "Derby County": "",
    "Derby County FC": "Derby County",
    "Derby Junction": "",
    "Derby Junction FC": "Derby Junction",
    "Derby Midland": "",
    "Derby St Luke's": "Derby St. Luke's",
    "Derby St. Luke’s": "Derby St. Luke's",
    "Derby Town": "Derby",
    "Derbyshire": "",
    "Desborough": "",
    "Desborough Town": "Desborough",
    "Dilettanti": "",
    "Dinnington": "",
    "Dinnington Athletic": "",
    "Distillery": "",
    "Doncaster": "",
    "Doncaster Rovers": "",
    "Dorchester Town": "Dorchester",
    "Dover": "",
    "Dover Athletic": "",
    "Dreadnought": "",
    "Droylsden": "",
    "Druids": "",
    "Dudley Town": "Dudley",
    "Dulwich": "",
    "Dulwich Hamlet": "",
    "Dunstable Town": "Dunstable",
    "Durham City": "",
    "Eagley": "",
    "Easington CW": "",
    "East Sheen": "",
    "East Thurrock United": "",
    "East Thurrock Utd": "East Thurrock United",
    "Eastbourne Borough": "",
    "Eastleigh": "",
    "Ebbsfleet United": "",
    "Ebbsfleet Utd": "Ebbsfleet United",
    "Eccles United": "",
    "Ecclesfield": "",
    "Eckington Works": "",
    "Egham": "",
    "Ellesmere Port Town": "Ellesmere Port",
    "Elswick Rangers": "",
    "Ely City": "",
    "Emley": "",
    "Enderby Town": "Enderby",
    "Enfield": "",
    "Enfield FC": "Enfield",
    "Epping Town": "Epping",
    "Epsom Town": "Epsom",
    "Esher Leopold": "",
    "Eton Ramblers": "",
    "Etonian Ramblers": "",
    "Evenwood Town": "Evenwood",
    "Everton": "",
    "Everton FC": "Everton",
    "Exeter City": "",
    "FA XI": "",
    "FC Accrington": "Accrington",
    "FC Acton": "Acton",
    "FC Aldershot": "Aldershot",
    "FC Alton": "Alton",
    "FC Altrincham": "Altrincham",
    "FC Alvechurch": "Alvechurch",
    "FC Andover": "Andover",
    "FC Apsley": "Apsley",
    "FC Arnold": "Arnold",
    "FC Arsenal": "Arsenal",
    "FC Arsenal London": "Arsenal London",
    "FC Ashington": "Ashington",
    "FC Attercliffe": "Attercliffe",
    "FC Aveley": "Aveley",
    "FC Barking": "Barking",
    "FC Barnet": "Barnet",
    "FC Barnsley": "Barnsley",
    "FC Barry": "Barry",
    "FC Bideford": "Bideford",
    "FC Bilston": "Bilston",
    "FC Birmingham": "Birmingham",
    "FC Birmingham Corporation Tramways": "Birmingham Corporation Tramways",
    "FC Bishop Auckland": "Bishop Auckland",
    "FC Bishop’s Stortford": "Bishop’s Stortford",
    "FC Blackpool": "Blackpool",
    "FC Bollington": "Bollington",
    "FC Bootle": "Bootle",
    "FC Boreham Wood": "Boreham Wood",
    "FC Boston": "Boston",
    "FC Bradshaw": "Bradshaw",
    "FC Brentford": "Brentford",
    "FC Brentwood": "Brentwood",
    "FC Brigg": "Brigg",
    "FC Bromley": "Bromley",
    "FC Brondesbury": "Brondesbury",
    "FC Burnley": "Burnley",
    "FC Burscough": "Burscough",
    "FC Bury": "Bury",
    "FC Buxton": "Buxton",
    "FC Calthorpe": "Calthorpe",
    "FC Canvey Island": "Canvey Island",
    "FC Chatham": "Chatham",
    "FC Chelsea": "Chelsea",
    "FC Chesham": "Chesham",
    "FC Chester": "Chester",
    "FC Chesterfield": "Chesterfield",
    "FC Chirk": "Chirk",
    "FC Chorley": "Chorley",
    "FC Church": "Church",
    "FC Clacton": "Clacton",
    "FC Clapton": "Clapton",
    "FC Clarence": "Clarence",
    "FC Clitheroe": "Clitheroe",
    "FC Cowlairs": "Cowlairs",
    "FC Cray Valley Paper Mills": "Cray Valley Paper Mills",
    "FC Croydon": "Croydon",
    "FC Crusaders": "Crusaders",
    "FC Crystal Palace": "Crystal Palace",
    "FC Curzon Ashton": "Curzon Ashton",
    "FC Dagenham": "Dagenham",
    "FC Darlington": "Darlington",
    "FC Dartford": "Dartford",
    "FC Darwen": "Darwen",
    "FC Davenham": "Davenham",
    "FC Derbyshire": "Derbyshire",
    "FC Distillery": "Distillery",
    "FC Dover": "Dover",
    "FC Dreadnought": "Dreadnought",
    "FC Droylsden": "Droylsden",
    "FC Druids": "Druids",
    "FC Dulwich": "Dulwich",
    "FC Eagley": "Eagley",
    "FC Eastleigh": "Eastleigh",
    "FC Ecclesfield": "Ecclesfield",
    "FC Enfield": "Enfield",
    "FC Everton": "Everton",
    "FC Fairfield": "Fairfield",
    "FC Farnborough": "Farnborough",
    "FC Farningham": "Farningham",
    "FC Finchley": "Finchley",
    "FC Fleetwood": "Fleetwood",
    "FC Folkestone": "Folkestone",
    "FC Forest School": "Forest School",
    "FC Formby": "Formby",
    "FC Fulham": "Fulham",
    "FC Gateshead": "Gateshead",
    "FC Gillingham": "Gillingham",
    "FC Gitanos": "Gitanos",
    "FC Glastonbury": "Glastonbury",
    "FC Glossop": "Glossop",
    "FC Goldenhill": "Goldenhill",
    "FC Gorleston": "Gorleston",
    "FC Great Harwood": "Great Harwood",
    "FC Great Lever": "Great Lever",
    "FC Gresham": "Gresham",
    "FC Halifax Town": "Halifax Town",
    "FC Halliwell": "Halliwell",
    "FC Hampton & Richmond Borough": "Hampton & Richmond Borough",
    "FC Haringey Borough": "Haringey Borough",
    "FC Havant & Waterlooville": "Havant & Waterlooville",
    "FC Hawks": "Hawks",
    "FC Hendon": "Hendon",
    "FC Henley": "Henley",
    "FC Hereford": "Hereford",
    "FC High Wycombe": "High Wycombe",
    "FC Horden CW": "Horden CW",
    "FC Horncastle": "Horncastle",
    "FC Hornchurch": "Hornchurch",
    "FC Horsham": "Horsham",
    "FC Hotspur": "Hotspur",
    "FC Hurst": "Hurst",
    "FC Hyde": "Hyde",
    "FC Ilford": "Ilford",
    "FC Jardines": "Jardines",
    "FC Jarrow": "Jarrow",
    "FC Kettering": "Kettering",
    "FC Kidderminster": "Kidderminster",
    "FC Kildare": "Kildare",
    "FC Kingstonian": "Kingstonian",
    "FC King’s Lynn": "King’s Lynn",
    "FC Leatherhead": "Leatherhead",
    "FC Leek": "Leek",
    "FC Leyton": "Leyton",
    "FC Leytonstone": "Leytonstone",
    "FC Leytonstone/Ilford": "Leytonstone/Ilford",
    "FC Liverpool": "Liverpool",
    "FC Llangollen": "Llangollen",
    "FC Lloyds (Sittingbourne)": "Lloyds (Sittingbourne)",
    "FC Loughborough": "Loughborough",
    "FC Lyndhurst": "Lyndhurst",
    "FC Lytham": "Lytham",
    "FC Maidenhead": "Maidenhead",
    "FC Margate": "Margate",
    "FC Marine": "Marine",
    "FC Marlow": "Marlow",
    "FC Merthyr Town": "Merthyr Town",
    "FC Metropolitan Police": "Metropolitan Police",
    "FC Mexborough": "Mexborough",
    "FC Middlesbrough": "Middlesbrough",
    "FC Millwall": "Millwall",
    "FC Minehead": "Minehead",
    "FC Minerva": "Minerva",
    "FC Mold": "Mold",
    "FC Morecambe": "Morecambe",
    "FC Mosquitos": "Mosquitos",
    "FC Mossley": "Mossley",
    "FC Needham Market": "Needham Market",
    "FC Nelson": "Nelson",
    "FC Netherfield": "Netherfield",
    "FC Newark": "Newark",
    "FC Newport (IOW)": "Newport (IOW)",
    "FC Newtown": "Newtown",
    "FC North Shields": "North Shields",
    "FC Nunhead": "Nunhead",
    "FC Old Foresters": "Old Foresters",
    "FC Orient": "Orient",
    "FC Oswestry": "Oswestry",
    "FC Owlerton": "Owlerton",
    "FC Padiham": "Padiham",
    "FC Penrith": "Penrith",
    "FC Pilgrims": "Pilgrims",
    "FC Poole": "Poole",
    "FC Portsmouth": "Portsmouth",
    "FC Queen’s Park": "Queen’s Park",
    "FC Ramblers": "Ramblers",
    "FC Ramsgate": "Ramsgate",
    "FC Rawtenstall": "Rawtenstall",
    "FC Reading": "Reading",
    "FC Reading Abbey": "Reading Abbey",
    "FC Reading Minster": "Reading Minster",
    "FC Redcar": "Redcar",
    "FC Redhill": "Redhill",
    "FC Remnants": "Remnants",
    "FC Renton": "Renton",
    "FC Rhyl": "Rhyl",
    "FC Ringmer": "Ringmer",
    "FC Rochdale": "Rochdale",
    "FC Rochester": "Rochester",
    "FC Romford": "Romford",
    "FC Rossendale": "Rossendale",
    "FC Runcorn": "Runcorn",
    "FC Salisbury": "Salisbury",
    "FC Saxons": "Saxons",
    "FC Scarborough": "Scarborough",
    "FC Shankhouse": "Shankhouse",
    "FC Sheffield": "Sheffield",
    "FC Shirebrook": "Shirebrook",
    "FC Sittingbourne": "Sittingbourne",
    "FC South Bank": "South Bank",
    "FC South Liverpool": "South Liverpool",
    "FC South Nordwood": "South Nordwood",
    "FC South Norwood": "South Norwood",
    "FC South Reading": "South Reading",
    "FC South Shields": "South Shields",
    "FC South Shore": "South Shore",
    "FC Southall": "Southall",
    "FC Southampton": "Southampton",
    "FC Southfield": "Southfield",
    "FC Southport": "Southport",
    "FC Southport Central": "Southport Central",
    "FC Southwick": "Southwick",
    "FC Spilsby": "Spilsby",
    "FC St Stephens": "St. Stephens",
    "FC St. Albans": "St. Albans",
    "FC Staveley": "Staveley",
    "FC Stevenage": "Stevenage",
    "FC Stockton": "Stockton",
    "FC Stoke": "Stoke",
    "FC Stourbridge": "Stourbridge",
    "FC Street": "Street",
    "FC Sunderland": "Sunderland",
    "FC Swifts": "Swifts",
    "FC Tamworth": "Tamworth",
    "FC Thames": "Thames",
    "FC Tilbury": "Tilbury",
    "FC Turton": "Turton",
    "FC United of Manchester": "United of Manchester",
    "FC Uxbridge": "Uxbridge",
    "FC Vauxhall Motors": "Vauxhall Motors",
    "FC Walsall": "Walsall",
    "FC Ware": "Ware",
    "FC Waterlooville": "Waterlooville",
    "FC Watford": "Watford",
    "FC Watford'": "Watford'",
    "FC Wealdstone": "Wealdstone",
    "FC Wembley": "Wembley",
    "FC West End": "West End",
    "FC West Manchester": "West Manchester",
    "FC West Stanley": "West Stanley",
    "FC Weston-Super-Mare": "Weston-Super-Mare",
    "FC Weymouth": "Weymouth",
    "FC Whitburn": "Whitburn",
    "FC Wimbledon": "Wimbledon",
    "FC Windsor & Eton": "Windsor & Eton",
    "FC Witton": "Witton",
    "FC Woking": "Woking",
    "FC Wombwell": "Wombwell",
    "FC Workington": "Workington",
    "FC Worthing": "Worthing",
    "FC Wrexham": "Wrexham",
    "FC Yiewsley": "Yiewsley",
    "FCc West End": "West End",
    "Fairfield": "",
    "Falmouth Town": "Falmouth",
    "Fareham": "",
    "Fareham Town": "Fareham",
    "Farnborough": "",
    "Farnborough Town": "Farnborough",
    "Farnham United Breweries": "",
    "Farningham": "",
    "Farsley Celtic": "",
    "Ferryhill Athletic": "",
    "Finchley": "",
    "Fisher Athletic": "",
    "Fishwick Ramblers": "",
    "Fleetwood": "",
    "Fleetwood Rangers": "",
    "Fleetwood Town": "Fleetwood",
    "Folkestone": "",
    "Folkestone & Shepway": "",
    "Folkestone Town": "Folkestone",
    "Ford United": "",
    "Forest Green": "",
    "Forest Green Rovers": "",
    "Forest School": "",
    "Formby": "",
    "Frickley Athletic": "",
    "Frickley Colliery": "",
    "Frome Town": "Frome",
    "Fulham": "",
    "Fulham FC": "Fulham",
    "Fulham Football Club": "",
    "Furness Vale Rovers": "",
    "Fylde": "",
    "Gainsboro Trinity": "",
    "Gainsborough Trinity": "",
    "Gateshead": "",
    "Gateshead Association": "",
    "Gateshead United": "",
    "Gillingham": "",
    "Gillingham FC": "Gillingham",
    "Gitanos": "",
    "Glasgow Rangers": "",
    "Glossop": "",
    "Glossop NE": "",
    "Glossop North End": "",
    "Gloucester City": "",
    "Goldenhill": "",
    "Golders Green": "",
    "Goole Town": "Goole",
    "Gorleston": "",
    "Gosforth and Coxlodge": "",
    "Gosport": "",
    "Gosport Borough": "",
    "Grantham": "",
    "Grantham Town": "Grantham",
    "Gravesend & Northfleet": "",
    "Gravesend United": "",
    "Grays Athletic": "",
    "Great Bridge Unity": "",
    "Great Harwood": "",
    "Great Lever": "",
    "Great Yarmouth Town": "Great Yarmouth",
    "Gresham": "",
    "Gresley Rovers": "",
    "Grey Friars": "",
    "Grimethorpe Rovers": "",
    "Grimsby & District": "",
    "Grimsby District": "",
    "Grimsby Pelham FC": "Grimsby Pelham",
    "Grimsby Town": "Grimsby",
    "Guildford": "",
    "Guildford City": "",
    "Guisborough Town": "Guisborough",
    "Guiseley": "",
    "Halesowen Town": "Halesowen",
    "Halifax": "",
    "Halifax Town": "Halifax",
    "Halliwell": "",
    "Halliwell FC": "Halliwell",
    "Hampstead Heathens": "",
    "Hampton & Richmond": "",
    "Hampton & Richmond Borough": "",
    "Hanover": "",
    "Hanover United": "",
    "Harborough Town": "Harborough",
    "Haringey Borough": "",
    "Harlow Town": "Harlow",
    "Harrogate Town": "Harrogate",
    "Harrow Borough": "",
    "Harrow Town": "Harrow",
    "Hartford St John's": "Hartford St. John's",
    "Hartford St John’s": "Hartford St. John's",
    "Hartford St. John’s": "Hartford St. John's",
    "Hartlepool": "",
    "Hartlepool United": "",
    "Hartlepool Utd": "Hartlepool United",
    "Hartlepools United": "Hartlepool United",
    "Harwich": "",
    "Harwich & Parkeston": "",
    "Haslingden Association": "",
    "Haslingden St. Marys": "",
    "Hastings & St Leonards United": "Hastings & St. Leonards United",
    "Hastings & St. Leonards United": "",
    "Hastings United": "",
    "Hastings Utd": "Hastings United",
    "Havant & Waterlooville": "",
    "Hawks": "",
    "Hayes": "",
    "Hayes & Yeading United": "",
    "Hayes & Yeading Utd": "Hayes & Yeading United",
    "Hayes FC": "Hayes",
    "Headington United": "",
    "Heanor Town": "Heanor",
    "Heart of Midlothian": "",
    "Hednesford Town": "Hednesford",
    "Heeley FC": "Heeley",
    "Hemel H. Town": "Hemel H.",
    "Hendon": "",
    "Henley": "",
    "Hereford": "",
    "Hereford United": "",
    "Hereford Utd": "Hereford United",
    "Hertfordshire Rangers": "",
    "Hertfs Rangers": "",
    "Herts Rangers": "",
    "Heybridge Swifts": "",
    "Heywood Central": "",
    "Higbury Union": "",
    "High Wycombe": "",
    "Highbury Union": "",
    "Higher Walton": "",
    "Hillingdon Borough": "",
    "Hinckley Athletic": "",
    "Hitchin": "",
    "Hitchin FC": "Hitchin",
    "Hitchin Town": "Hitchin",
    "Hoddesdon Town": "Hoddesdon",
    "Holbeach United": "",
    "Holiday's Sports": "",
    "Horden Athletic": "",
    "Horden CW": "",
    "Horden Colliery Welfare": "",
    "Horncastle": "",
    "Hornchurch": "",
    "Horsham": "",
    "Horwich RMI": "",
    "Hotspur": "",
    "Hounslow Town": "Hounslow",
    "Hucknall St Johns": "Hucknall St. John's",
    "Hucknall St. John’s": "Hucknall St. John's",
    "Huddersfield": "",
    "Huddersfield Town": "Huddersfield",
    "Hull City": "",
    "Hull Town": "Hull",
    "Hungerford Town": "Hungerford",
    "Hurst": "",
    "Hyde": "",
    "Hyde United": "",
    "Hyde Utd": "Hyde United",
    "Ilford": "",
    "Ilkeston Town": "Ilkeston",
    "Inghilterra": "",
    "Ipswich": "",
    "Ipswich Town": "Ipswich",
    "Irthlingborough Town": "Irthlingborough",
    "Irwell Springs": "",
    "Jardines": "",
    "Jarrow": "",
    "Kells United": "",
    "Kendal Town": "Kendal",
    "Kettering": "",
    "Kettering Town": "Kettering",
    "Kidderminster": "",
    "Kidderminster Harriers": "",
    "Kildare": "",
    "King's Lynn": "",
    "King's Lynn Town": "King's Lynn",
    "Kingstonian": "",
    "Kingstonian FC": "Kingstonian",
    "King’s Lynn Town": "King’s Lynn",
    "Kirkby Town": "Kirkby",
    "Lancaster City": "",
    "Lancaster Town": "Lancaster",
    "Lancing Old Boys": "",
    "Layton": "",
    "Leamington": "",
    "Leatherhead": "",
    "Leeds": "",
    "Leeds City": "",
    "Leeds United": "",
    "Leeds Utd": "Leeds United",
    "Leek": "",
    "Leicester City": "",
    "Leicester Fosse": "",
    "Leigh RMI": "",
    "Leyland Motors": "",
    "Leyton": "",
    "Leyton Orient": "",
    "Leyton-Wingate": "",
    "Leytonstone": "",
    "Leytonstone & Ilford": "",
    "Linby Colliery": "",
    "Lincoln Albion": "",
    "Lincoln City": "",
    "Lincoln Lindum": "",
    "Lincoln Ramblers": "",
    "Lincoln United": "",
    "Linfield Athletic": "",
    "Linfield Athletic Club": "",
    "Liverpool": "",
    "Liverpool FC": "Liverpool",
    "Liverpool Ramblers": "",
    "Liverpool Stanley": "",
    "Llanelli": "",
    "Llanelly": "Llanelli",
    "Llangollen Town": "Llangollen",
    "Lockwood Brothers": "",
    "London Caledonian": "",
    "London Caledonians": "",
    "London Olympic": "",
    "London Paper Mills": "",
    "London Rangers": "",
    "Long Eaton Rangers": "",
    "Long Eaton Rangers FC": "Long Eaton Rangers",
    "Loughborough": "",
    "Loughborough United": "",
    "Lovells Athletic": "",
    "Low Moor": "",
    "Lower Darwen": "",
    "Lowesoft": "",
    "Lowestoft Town": "Lowestoft",
    "Luddendenfoot": "",
    "Luton Town": "Luton",
    "Luton Wanderers": "",
    "Lyndhurst": "",
    "Lytham": "",
    "MK Dons": "Milton Keynes Dons",
    "Macclesfield Town": "Macclesfield",
    "Maidenhead": "",
    "Maidenhead United": "",
    "Maidenhead Utd": "Maidenhead United",
    "Maidstone United": "",
    "Maidstone Utd": "Maidstone United",
    "Maldon & Tiptree": "",
    "Manchester": "",
    "Manchester Association": "",
    "Manchester Central": "",
    "Manchester City": "",
    "Manchester United": "",
    "Manchester Utd": "Manchester United",
    "Manfield Town": "Manfield",
    "Mansfield Town": "Mansfield",
    "March Town United": "",
    "Margate": "",
    "Marine": "",
    "Marine AFC": "Marine",
    "Marlow": "",
    "Matlock": "",
    "Matlock Town": "Matlock",
    "Meborough": "",
    "Mellors": "",
    "Mellors Limited": "",
    "Meltham Mills": "",
    "Merstham": "",
    "Merthyr Town": "Merthyr",
    "Merthyr Tydfil": "",
    "Metropolitan Police": "",
    "Mexborough": "",
    "Mexborough Athletic": "",
    "Middlesbro": "",
    "Middlesbrough": "",
    "Middlesbrough FC": "Middlesbrough",
    "Middlesbrough Ironopolis": "",
    "Millwall": "",
    "Millwall Athletic": "",
    "Millwall Rovers": "",
    "Milton Keynes Dons": "",
    "Milwall FC": "Milwall",
    "Minehead": "",
    "Minerva": "",
    "Mitchell St George's": "Mitchell's St. George's",
    "Mitchell St. George's": "Mitchell's St. George's",
    "Mitchell St. George’s FC": "Mitchell's St. George's",
    "Mitchell's St George's": "Mitchell's St. George's",
    "Mitchell’s St. George’s": "Mitchell's St. George's",
    "Mold Town": "Mold",
    "Moor Green": "",
    "Morecambe": "",
    "Morpeth Harriers": "",
    "Morton Rangers": "",
    "Mosquitoes": "",
    "Mosquitos": "",
    "Mossley": "",
    "Mossley F.C.": "",
    "Nantwich Town": "Nantwich",
    "Needham Market": "",
    "Nelson": "",
    "Netherfield": "",
    "Netherfield (Kendal)": "Netherfield",
    "New Brighto": "New Brighton",
    "New Brighton": "",
    "New Brighton Athletic": "",
    "New Brighton Tower": "",
    "New Brompton": "",
    "New Crusaders": "",
    "Newark": "",
    "Newark Town": "Newark",
    "Newbury Town": "Newbury",
    "Newcastle": "Newcastle United",
    "Newcastle East End": "",
    "Newcastle Town": "Newcastle",
    "Newcastle United": "",
    "Newcastle Utd": "Newcastle United",
    "Newcastle West End": "",
    "Newport (IOW)": "Newport",
    "Newport (IoW)": "Newport",
    "Newport County": "",
    "Newport IOW": "Newport",
    "Newton Heath": "",
    "Newtown": "",
    "Nomads": "",
    "North Shields": "",
    "Northampton": "",
    "Northampton Town": "Northampton",
    "Northern Nomads": "",
    "Northfleet": "",
    "Northfleet United": "",
    "Northwich Victoria": "",
    "Norton United": "",
    "Norwich City": "",
    "Nott'ham Forest": "Nottingham Forest",
    "Nottingham Forest": "",
    "Nottingham Forest FC": "Nottingham Forest",
    "Nottingham Forrest": "Nottingham Forest",
    "Nottingham Wanderers": "",
    "Notts County": "",
    "Notts County FC": "Notts County",
    "Notts County Football Club": "Notts County",
    "Notts Olympic": "",
    "Notts Rangers": "",
    "Notts Rangers FC": "Notts Rangers",
    "Notts Swifts": "",
    "Notts Wanderers": "",
    "Nuneaton Borough": "",
    "Nuneaton Borough AFC": "Nuneaton Borough",
    "Nuneaton Town": "Nuneaton",
    "Nunhead": "",
    "Old Brightonians": "",
    "Old Brightonians FC": "Old Brightonians",
    "Old Carthusians": "",
    "Old Carthusians FC": "Old Carthusians",
    "Old Etonians": "",
    "Old Foresters": "",
    "Old Foresters FC": "Old Foresters",
    "Old Harrovians": "",
    "Old Harrovians FC": "Old Harrovians",
    "Old Johnians": "",
    "Old St Mark's": "Old St. Mark's",
    "Old St. Mark’s": "Old St. Mark's",
    "Old Westministers": "",
    "Old Westminsters": "",
    "Old Westminsters FC": "Old Westminsters",
    "Old Wykehamist": "",
    "Old Wykehamists": "",
    "Oldbury Town": "Oldbury",
    "Oldham Athletic": "",
    "Olympic": "",
    "Olympic London": "",
    "Orient": "",
    "Osberton Radiator": "",
    "Ossett Town": "Ossett",
    "Oswaldtwistle Rovers": "",
    "Oswardthistle Rovers": "",
    "Oswestry": "",
    "Oswestry Town": "Oswestry",
    "Over Wanderers": "",
    "Owlerton": "",
    "Oxford City": "",
    "Oxford United": "",
    "Oxford University": "",
    "Oxford University AFC": "Oxford University",
    "Oxford Utd": "Oxford United",
    "Padiham": "",
    "Panthers": "",
    "Panthers FC": "Panthers",
    "Park Grange": "",
    "Partick Thistle": "",
    "Penrith": "",
    "Peterborough & Fletton United": "Peterborough United",
    "Peterborough United": "",
    "Peterborough Utd": "Peterborough United",
    "Peterborough and Fletton United": "Peterborough United",
    "Petersborough United": "Peterborough United",
    "Phoenix Bessemer": "",
    "Pilgrims": "",
    "Pilkington Recreation": "",
    "Plymouth": "",
    "Plymouth Argyle": "Plymouth",
    "Poole": "",
    "Poole Town": "Poole",
    "Port Vale": "",
    "Port Vale FC": "Port Vale",
    "Portsmouth": "",
    "Portsmouth FC": "Portsmouth",
    "Prescot Cables": "",
    "Pressed Steel": "",
    "Preston": "",
    "Preston N.E.": "Preston North End",
    "Preston North End": "",
    "Preston North End FC": "Preston North End",
    "Professionisti": "",
    "Providence": "",
    "QPR": "Queens Park Rangers",
    "Queen's Park": "Queens Park Rangers",
    "Queen's Park Ranger": "Queens Park Rangers",
    "Queen's Park Rangers": "Queens Park Rangers",
    "Queens Park Rangers": "",
    "Ramblers": "",
    "Ramsgate": "",
    "Ramsgate Athletic": "",
    "Rangers": "",
    "Rangers (London)": "",
    "Rawmarsh Welfare": "",
    "Rawtenstall": "",
    "Reading": "",
    "Reading Abbey": "",
    "Reading Abbey FC": "Reading Abbey",
    "Reading FC": "Reading",
    "Reading Hornets": "",
    "Reading Minster": "",
    "Reading Minster FC": "Reading Minster",
    "Redbridge": "",
    "Redcar": "",
    "Redcar and Coatham": "",
    "Redditch United": "",
    "Redhill": "",
    "Reigate Priory": "",
    "Remnants": "",
    "Renton": "",
    "Reyrolles": "",
    "Rhyl": "",
    "Rhyl Athletic": "Rhyl",
    "Ringmer": "",
    "Rochdale": "",
    "Rochdale AFC": "Rochdale",
    "Rochester": "",
    "Romford": "",
    "Rossendale": "",
    "Rossendale United": "",
    "Rossington Main": "",
    "Roterham United": "",
    "Rotheram United": "",
    "Rotherham County": "",
    "Rotherham Town": "Rotherham",
    "Rotherham United": "",
    "Rotherham Utd": "Rotherham United",
    "Royal Arsenal": "",
    "Royal Engineers": "",
    "Royal Engineers AFC": "Royal Engineers",
    "Royal Engineers FC": "Royal Engineers",
    "Runcorn": "",
    "Rushall Olympic": "",
    "Rushden & Diamonds": "",
    "Ryde Sports": "",
    "Ryhope Colliery Welfare": "",
    "Saffron Walden": "",
    "Saffron Walden Town": "Saffron Walden",
    "Salford City": "",
    "Salisbury": "",
    "Salisbury City": "",
    "Saxons": "",
    "Scarborough": "",
    "Scarborough Athl.": "",
    "Scarborough Athletic": "",
    "Scarborough FC": "Scarborough",
    "Scotswood": "",
    "Scunthorpe & Lindsey United": "",
    "Scunthorpe & Lindsey Utd": "Scunthorpe & Lindsey United",
    "Scunthorpe United": "",
    "Scunthorpe Utd": "Scunthorpe United",
    "Selby Town": "Selby",
    "Shankhouse": "",
    "Shaw Lane": "",
    "Sheffield": "",
    "Sheffield Heeley": "",
    "Sheffield Providence": "",
    "Sheffield United": "",
    "Sheffield Utd": "Sheffield United",
    "Sheffield Wednesday": "",
    "Sheffield Weds": "Sheffield Wednesday",
    "Sheppey United": "",
    "Sheppey Utd": "Sheppey United",
    "Shepshed Dynamo": "",
    "Shildon": "",
    "Shildon College": "",
    "Shirebrook": "",
    "Shrewsbury Town": "Shrewsbury",
    "Shropshire Wanderers": "",
    "Sittingbourne": "",
    "Skegness Town": "Skegness",
    "Skelmersdale United": "",
    "Skelmersdale Utd": "Skelmersdale United",
    "Slough Swifts FC": "Slough Swifts",
    "Slough Town": "Slough",
    "Slough United": "",
    "Small Heath": "",
    "Small Heath Alliance": "",
    "Small Heath FC": "Small Heath",
    "Solihull Borough": "",
    "Solihull Moors": "",
    "South Bank": "",
    "South Bank St Peters": "South Bank St. Peters",
    "South Bank St. Peters": "",
    "South Kirkby Colliery": "",
    "South Liverpool": "",
    "South Norwood": "",
    "South Reading": "",
    "South Shields": "",
    "South Shore": "",
    "South Shore FC": "South Shore",
    "Southall": "",
    "Southampton": "",
    "Southampton FC": "Southampton",
    "Southampton St Mary's": "Southampton St. Mary's",
    "Southampton St. Mary’s": "Southampton St. Mary's",
    "Southend United": "",
    "Southend Utd": "Southend United",
    "Southfield": "",
    "Southill Park": "",
    "Southport": "",
    "Southport Central": "",
    "Spalding United": "",
    "Spennymoor": "",
    "Spennymoor Town": "Spennymoor",
    "Spennymoor United": "",
    "Spennymoor Utd": "Spennymoor United",
    "Spilsby": "",
    "Spital": "",
    "St Alban's": "St. Alban's",
    "St Albans": "St. Alban's",
    "St Albans City": "St. Alban's",
    "St Bart's Hospital": "St. Bart’s Hospital",
    "St George's": "St. George's",
    "St Neots Town": "St. Neots Town",
    "St Peter's Institute": "St. Peter’s Institute",
    "St Peter’s Institute FC": "St. Peter’s Institute",
    "St. Albans": "St. Alban's",
    "St. Bart’s Hospital FC": "St. Bart’s Hospital",
    "St. Neots Town": "St. Neots Town",
    "St. Peter's Institute": "",
    "St. Stephen's": "",
    "Stafford Rangers": "",
    "Stafford Road": "Stafford Road Works",
    "Stafford Road Works": "",
    "Staines Town": "Staines",
    "Stalybridge Celtic": "",
    "Stalybridge Rovers": "",
    "Stamford": "",
    "Stanley United": "",
    "Staple Hill": "",
    "Staveley": "",
    "Stevenage": "",
    "Stevenage Borough": "",
    "Stevenage Borough FC": "Stevenage Borough",
    "Stockport Co": "Stockport County",
    "Stockport Country": "Stockport County",
    "Stockport County": "",
    "Stockport Sports": "Stockport County",
    "Stockton": "",
    "Stoke": "Stoke City",
    "Stoke City": "",
    "Stoke City Football Club": "Stoke City",
    "Stourbridge": "",
    "Stratford Town": "Stratford",
    "Street": "",
    "Sudbury": "",
    "Sudbury Town": "Sudbury",
    "Sunderland": "",
    "Sunderland AFC": "Sunderland",
    "Sunderland Albion": "",
    "Sunderland Albion FC": "Sunderland Albion",
    "Sutton Coldfield Town": "Sutton Coldfield",
    "Sutton Junction": "",
    "Sutton Town": "Sutton",
    "Sutton Town AFC": "Sutton Town",
    "Sutton United": "",
    "Sutton Utd": "Sutton United",
    "Swansea": "",
    "Swansea City": "",
    "Swansea Town": "Swansea",
    "Swifts": "",
    "Swindon Town": "Swindon",
    "Tamworth": "",
    "Taunton Town": "Taunton",
    "Telford United": "",
    "Telford Utd": "Telford United",
    "Thames": "",
    "The Arsenal": "Arsenal",
    "The Birmingham Club": "Birmingham Club",
    "The Wednesday": "Sheffield Wednesday",
    "The Wednesday FC": "Sheffield Wednesday",
    "Third Lanark": "",
    "Thornycrofts (Woolston)": "Thornycrofts Woolston",
    "Thornycrofts Woolston": "",
    "Throckley Welfare": "",
    "Tilbury": "",
    "Tiverton Town": "Tiverton",
    "Ton Pentre": "",
    "Tonbridge": "Tonbridge Angels",
    "Tonbridge Angels": "",
    "Tooting & Mitcham United": "",
    "Torquay United": "",
    "Torquay Utd": "Torquay United",
    "Tottenham": "",
    "Tottenham Hotspur": "Tottenham",
    "Tow Law Town": "",
    "Tranmere": "Tranmere Rovers",
    "Tranmere Rovers": "",
    "Trimdon Grange Colliery": "",
    "Trowbridge Town": "",
    "Truro City": "",
    "Tunbridge Wells Rangers": "",
    "Tunbridge Wells United": "",
    "Turton": "",
    "Tyne Association": "",
    "Union": "",
    "United Hospital": "United Hospitals",
    "United Hospitals": "",
    "United London Scottish": "",
    "United London Swifts": "",
    "Upton Colliery": "",
    "Upton Park": "",
    "Upton Park FC": "Upton Park",
    "Upton Rangers": "",
    "Usworth Colliery": "",
    "Utd of Manchester": "Manchester United",
    "Uxbridge": "",
    "VS Rugby": "",
    "Vauxhall Motors (Luton)": "",
    "Walker Celtic": "",
    "Walsall": "",
    "Walsall FC": "Walsall",
    "Walsall Swifts": "",
    "Walsall Town": "Walsall",
    "Walsall Town Swifts": "",
    "Walsall Town Swifts FC": "Walsall Town Swifts",
    "Walthamstow": "",
    "Walthamstow Avenue": "",
    "Walton & Hersham": "",
    "Walton-On-Thames": "",
    "Wanderers": "",
    "Wanderers FC": "Wanderers",
    "Ware": "",
    "Warrington Town": "Warrington",
    "Warwick County": "",
    "Washington Chemical Works": "",
    "Waterlooville": "",
    "Watford": "",
    "Watford FC": "Watford",
    "Watford Rovers": "",
    "Wath Athletic": "",
    "Wealdstone": "",
    "Wednesbury Old Athletic": "",
    "Wednesbury Strollers": "",
    "Wednesbury Town": "Wednesbury",
    "Welling United": "",
    "Wellingborough Town": "Wellingborough",
    "Wellington": "",
    "Wellington St George's": "Wellington St. George's",
    "Wellington St. George’s": "Wellington St. George's",
    "Wellington Town": "Wellington",
    "Welton Rovers": "",
    "Welwyn Garden City": "",
    "Wembley": "",
    "West Auckland Town": "West Auckland",
    "West Beomwich Albion": "West Bromwich Albion",
    "West Brom": "West Bromwich Albion",
    "West Bromwich": "West Bromwich Albion",
    "West Bromwich Albion": "",
    "West Bromwich Albion FC": "West Bromwich Albion",
    "West End": "",
    "West Ham": "West Ham United",
    "West Ham United": "",
    "West Ham Utd": "West Ham United",
    "West Manchester": "",
    "West Stanley": "",
    "Westbury United": "",
    "Westfields": "",
    "Weston-Super-Mare": "",
    "Weston-super-Mare": "Weston-Super-Mare",
    "Weybridge": "Weybridge Swallows",
    "Weybridge Swallows": "",
    "Weymouth": "",
    "Whitburn": "",
    "Whitby Town": "Whitby",
    "Whitehawk": "",
    "Whitley & Monkseaton": "",
    "Whitley Bay": "",
    "Wigan": "Wigan Athletic",
    "Wigan Athletic": "",
    "Wigan Borough": "",
    "Wigan County": "",
    "Willenhall Town": "Willenhall",
    "Willington": "",
    "Wilmslow Albion": "",
    "Wimbledon": "",
    "Wimbledon FC": "Wimbledon",
    "Wimborne Town": "Wimborne",
    "Windsor": "",
    "Windsor & Eton": "",
    "Windsor Home Park": "",
    "Winsford United": "",
    "Wirksop": "",
    "Wisbech Town": "Wisbech",
    "Witney United": "",
    "Witton": "",
    "Witton Albion": "",
    "Witton West End FC": "Witton West End",
    "Woking": "",
    "Woking FC": "Woking",
    "Wokingham Town": "Wokingham",
    "Wolverhampton": "Wolverhampton Wanderers",
    "Wolverhampton Waderers": "Wolverhampton Wanderers",
    "Wolverhampton Wanderers": "",
    "Wolverhampton Wanderers FC": "Wolverhampton Wanderers",
    "Wolves": "Wolverhampton Wanderers",
    "Wood Grange": "",
    "Woodford Bridge": "",
    "Woodford Town": "Woodford",
    "Woodford Wells": "",
    "Woolwich Arsenal": "",
    "Worcester City": "",
    "Workington": "",
    "Worksop Town": "Worksop",
    "Worthing": "",
    "Wrexham": "",
    "Wrexham AFC": "Wrexham",
    "Wrexham Olympic": "",
    "Wycombe": "",
    "Wycombe Wanderers": "",
    "Yate Town": "Yate",
    "Yeading": "",
    "Yeovil & Petter's United": "",
    "Yeovil & Petters United": "",
    "Yeovil & Petter’s United": "",
    "Yeovil Town": "Yeovil",
    "Yeovil and Petters United": "",
    "Yiewsley": "",
    "York City": "",
    "Yorks Amateurs": "",
    "Yorkshire Amateur": ""
}

// Funzione per normalizzare i nomi delle squadre
export default function normalizeTeamName(teamName: string) {
    return teamNormalizationMap[teamName] || teamName;
}